In [31]:
#import
import pandas as pd
from sklearn.model_selection import train_test_split  #データの分割

from sklearn.preprocessing import StandardScaler #標準化
from sklearn.model_selection import KFold #K分割交差検証
from sklearn.model_selection import cross_validate  #K分割交差検証

from sklearn.linear_model import LinearRegression #回帰
from sklearn.preprocessing import PolynomialFeatures  #交互作用特徴量
from sklearn.linear_model import Ridge  #リッジ回帰
from sklearn.linear_model import Lasso  #ラッソ回帰
from sklearn.tree import DecisionTreeRegressor  #回帰木

from statsmodels.stats.outliers_influence import variance_inflation_factor  #VIF
from sklearn.decomposition import PCA  #PCA

In [32]:
#データフレームの読み込み
'''
df1 VIFの高さを解消するために一部の列を消去する前のデータフレーム
df2 〃した後のデータフレーム

以降は基本的にdf2を用いて分析を行う。
sc_x,df_yはdf2を基に作成する。
ただし、必要があればdf1も利用する。
'''
df1 = pd.read_csv('datafiles/df1_all_col.csv')
df2 = pd.read_csv('datafiles/df2_after_drop.csv')

sc_x = df2.drop(['SalePrice'], axis = 1)
df_y = pd.DataFrame(df2['SalePrice'])

In [33]:
print(df2.columns)

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtUnfSF',
       ...
       'PoolQC_Fa', 'PoolQC_Gd', 'BsmtQual_Fa', 'BsmtQual_Gd', 'BsmtQual_NA',
       'BsmtQual_TA', 'LandContour_HLS', 'LandContour_Low', 'LandContour_Lvl',
       'SalePrice'],
      dtype='object', length=250)

In [34]:
#K分割交差検証のための準備
kf=KFold(n_splits=5, shuffle=True, random_state=0)

In [35]:
#各種モデルの作成

#重回帰
model1 = LinearRegression()
model1.fit(sc_x, df_y)

#リッジ回帰
model2 = Ridge(alpha = 100)
model2.fit(sc_x, df_y)

#ラッソ回帰
model3 = Lasso(alpha = 100)
model3.fit(sc_x, df_y)

#回帰木
model4 = DecisionTreeRegressor(max_depth = 10, random_state = 0)
model4.fit(sc_x, df_y)

DecisionTreeRegressor(max_depth=10, random_state=0)

In [36]:
#依然として多重共線性は高いため、今後も多重共線性の解消を目指す。

#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 100]
display(df_high_vif)

      VIF_Factor             features
22   2178.616803          GarageYrBlt
107   115.837730  Exterior1st_VinylSd
113   283.746702        GarageCond_TA
123  2202.752816      GarageFinish_NA
182   105.805972  Exterior2nd_VinylSd
185   165.010225      RoofStyle_Gable
187   153.477931        RoofStyle_Hip
193   233.699047        GarageQual_TA
236   960.199106       MiscFeature_NA
238   802.650747     MiscFeature_Shed

In [37]:
#一列dropしてみる
sc_x = sc_x.drop(['GarageFinish_NA'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 100]
display(df_high_vif)

result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor             features
107  115.837134  Exterior1st_VinylSd
113  282.411676        GarageCond_TA
181  105.785392  Exterior2nd_VinylSd
184  164.851995      RoofStyle_Gable
186  153.344617        RoofStyle_Hip
192  233.384665        GarageQual_TA
235  959.675823       MiscFeature_NA
237  802.110365     MiscFeature_Shed

完成したmodel2のスコア＝0.7788228561257451

In [38]:
#一列dropしてみる
sc_x = sc_x.drop(['MiscFeature_NA'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 100]
display(df_high_vif)

result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor             features
107  115.678525  Exterior1st_VinylSd
113  282.329291        GarageCond_TA
181  105.733960  Exterior2nd_VinylSd
184  164.851570      RoofStyle_Gable
186  153.344550        RoofStyle_Hip
192  233.363856        GarageQual_TA

完成したmodel2のスコア＝0.7788175817571735

In [39]:
#3列dropしてみる
sc_x = sc_x.drop(['Exterior2nd_VinylSd', 'GarageCond_TA', 'RoofStyle_Gable'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 100]
display(df_high_vif)

result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

Empty DataFrame
Columns: [VIF_Factor, features]
Index: []

完成したmodel2のスコア＝0.7785744518848133

In [40]:
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]

df_high_vif.sort_values('VIF_Factor', ascending=False)

     VIF_Factor               features
76    90.503234           ExterCond_TA
34    81.381629      GarageType_Attchd
74    76.363708           ExterCond_Gd
89    74.401726       RoofMatl_CompShg
38    65.809905      GarageType_Detchd
189   54.715176          GarageQual_TA
22    53.575630            GarageYrBlt
209   51.800551           SaleType_New
103   51.486680    Exterior1st_MetalSd
225   49.162602            MSZoning_RL
43    49.072046  SaleCondition_Partial
10    43.956054            TotalBsmtSF
130   40.031633           Heating_GasA
175   39.593469    Exterior2nd_MetalSd
8     37.100650             BsmtFinSF1
9     35.761214              BsmtUnfSF
0     34.873864             MSSubClass
101   34.013490    Exterior1st_HdBoard
100   33.156910    Exterior1st_CemntBd
226   32.885288            MSZoning_RM
93    32.648732       RoofMatl_Tar&Grv
155   32.531442          MasVnrType_NA
172   29.027080    Exterior2nd_CmentBd
107   28.505460    Exterior1st_VinylSd
154   28.089114     MasVnrType_BrkFace
108   27.864077    Exterior1st_Wd Sdng
118   27.322952         FireplaceQu_NA
13    25.309143              GrLivArea
131   24.150621           Heating_GasW
58    22.874896     Neighborhood_NAmes
11    21.162622               1stFlrSF
36    20.879792     GarageType_BuiltIn
186   20.646135          GarageQual_Fa
173   20.591755    Exterior2nd_HdBoard
63    19.026102   Neighborhood_OldTown
46    18.806107           ExterQual_TA
153   18.789566       BsmtFinType2_Unf
95    18.143395       RoofMatl_WdShngl
73    17.526563           ExterCond_Fa
223   17.397190            MSZoning_FV
104   17.378668    Exterior1st_Plywood
94    17.015940       RoofMatl_WdShake
180   16.863430    Exterior2nd_Wd Sdng
222   16.580265        BldgType_TwnhsE
117   15.414809         FireplaceQu_Gd
5     14.713069              YearBuilt
120   14.515866         FireplaceQu_TA
45    14.458799           ExterQual_Gd
51    13.848010   Neighborhood_CollgCr
213   13.559739      HouseStyle_1Story
177   13.209854    Exterior2nd_Plywood
239   13.180815            BsmtQual_NA
67    12.837224   Neighborhood_Somerst
240   11.979665            BsmtQual_TA
194   11.886476        Condition2_Norm
156   11.832241       MasVnrType_Stone
53    11.626184   Neighborhood_Edwards
137   10.825210         KitchenQual_TA
132   10.723085           Heating_Grav
129   10.097838         Functional_Typ

In [41]:
#3列dropしてみる
sc_x = sc_x.drop(['ExterCond_TA', 'GarageType_Attchd'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
df_high_vif.sort_values('VIF_Factor', ascending=False)

     VIF_Factor               features
87    74.294750       RoofMatl_CompShg
187   54.692519          GarageQual_TA
207   51.798480           SaleType_New
101   51.119943    Exterior1st_MetalSd
42    49.071613  SaleCondition_Partial
223   49.044799            MSZoning_RL
10    43.948652            TotalBsmtSF
128   40.008059           Heating_GasA
173   39.335555    Exterior2nd_MetalSd
8     37.071897             BsmtFinSF1
9     35.731590              BsmtUnfSF
22    35.464462            GarageYrBlt
0     34.836645             MSSubClass
99    33.819178    Exterior1st_HdBoard
98    32.987842    Exterior1st_CemntBd
224   32.768803            MSZoning_RM
91    32.608835       RoofMatl_Tar&Grv
153   32.516718          MasVnrType_NA
170   28.944317    Exterior2nd_CmentBd
105   28.428503    Exterior1st_VinylSd
152   28.086050     MasVnrType_BrkFace
106   27.674552    Exterior1st_Wd Sdng
116   27.317552         FireplaceQu_NA
13    25.262063              GrLivArea
129   24.140066           Heating_GasW
57    22.850034     Neighborhood_NAmes
11    21.160379               1stFlrSF
184   20.640083          GarageQual_Fa
171   20.561693    Exterior2nd_HdBoard
62    18.996966   Neighborhood_OldTown
45    18.785049           ExterQual_TA
151   18.775727       BsmtFinType2_Unf
93    18.123505       RoofMatl_WdShngl
221   17.340506            MSZoning_FV
102   17.304836    Exterior1st_Plywood
92    16.995623       RoofMatl_WdShake
178   16.822239    Exterior2nd_Wd Sdng
220   16.572072        BldgType_TwnhsE
115   15.413045         FireplaceQu_Gd
5     14.712815              YearBuilt
118   14.514807         FireplaceQu_TA
44    14.455322           ExterQual_Gd
50    13.844727   Neighborhood_CollgCr
211   13.538958      HouseStyle_1Story
175   13.193579    Exterior2nd_Plywood
237   13.179801            BsmtQual_NA
66    12.828973   Neighborhood_Somerst
238   11.947524            BsmtQual_TA
192   11.877318        Condition2_Norm
154   11.829309       MasVnrType_Stone
52    11.607898   Neighborhood_Edwards
135   10.776370         KitchenQual_TA
130   10.716540           Heating_Grav
127   10.096010         Functional_Typ

In [42]:
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

完成したmodel2のスコア＝0.7786656098208713

In [43]:
#4列dropしてみる
sc_x = sc_x.drop(['RoofMatl_CompShg', 'GarageQual_TA', 'SaleType_New', 'Exterior1st_MetalSd'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

     VIF_Factor              features
219   48.946791           MSZoning_RL
10    43.205565           TotalBsmtSF
126   39.953988          Heating_GasA
8     36.797813            BsmtFinSF1
9     35.658095             BsmtUnfSF
0     34.745525            MSSubClass
220   32.669914           MSZoning_RM
151   32.515975         MasVnrType_NA
97    28.835127   Exterior1st_CemntBd
150   28.079813    MasVnrType_BrkFace
168   28.019531   Exterior2nd_CmentBd
114   27.075910        FireplaceQu_NA
13    24.909164             GrLivArea
127   24.117283          Heating_GasW
57    22.839742    Neighborhood_NAmes
103   21.745307   Exterior1st_VinylSd
11    21.004793              1stFlrSF
62    18.971534  Neighborhood_OldTown
149   18.758056      BsmtFinType2_Unf
45    18.737500          ExterQual_TA
217   17.270353           MSZoning_FV
98    16.946186   Exterior1st_HdBoard
216   16.547138       BldgType_TwnhsE
169   16.035793   Exterior2nd_HdBoard
113   15.364833        FireplaceQu_Gd
104   14.751391   Exterior1st_Wd Sdng
5     14.506338             YearBuilt
116   14.466238        FireplaceQu_TA
44    14.393154          ExterQual_Gd
50    13.826444  Neighborhood_CollgCr
176   13.665718   Exterior2nd_Wd Sdng
207   13.272611     HouseStyle_1Story
233   12.974457           BsmtQual_NA
66    12.748268  Neighborhood_Somerst
171   12.255745   Exterior2nd_MetalSd
234   11.892308           BsmtQual_TA
189   11.861105       Condition2_Norm
152   11.825406      MasVnrType_Stone
52    11.601421  Neighborhood_Edwards
173   10.894903   Exterior2nd_Plywood
133   10.722481        KitchenQual_TA
128   10.703671          Heating_Grav
125   10.073144        Functional_Typ

In [44]:
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

完成したmodel2のスコア＝0.7786075560896846

In [45]:
#4列dropしてみる
sc_x = sc_x.drop(['MSZoning_RL', 'TotalBsmtSF', 'Heating_GasA', 'BsmtFinSF1'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

     VIF_Factor              features
0     34.608125            MSSubClass
148   32.438191         MasVnrType_NA
95    28.758254   Exterior1st_CemntBd
147   28.017892    MasVnrType_BrkFace
165   27.951783   Exterior2nd_CmentBd
112   27.019800        FireplaceQu_NA
11    24.884128             GrLivArea
55    22.784311    Neighborhood_NAmes
101   21.672533   Exterior1st_VinylSd
43    18.709625          ExterQual_TA
60    18.441342  Neighborhood_OldTown
96    16.883913   Exterior1st_HdBoard
213   16.458552       BldgType_TwnhsE
166   15.852241   Exterior2nd_HdBoard
9     15.555781              1stFlrSF
111   15.362034        FireplaceQu_Gd
102   14.709670   Exterior1st_Wd Sdng
114   14.447351        FireplaceQu_TA
42    14.383612          ExterQual_Gd
5     14.364998             YearBuilt
48    13.782718  Neighborhood_CollgCr
173   13.542481   Exterior2nd_Wd Sdng
204   13.188947     HouseStyle_1Story
64    12.717934  Neighborhood_Somerst
168   12.205471   Exterior2nd_MetalSd
230   11.847475           BsmtQual_TA
149   11.780496      MasVnrType_Stone
186   11.754728       Condition2_Norm
50    11.545700  Neighborhood_Edwards
146   11.440429      BsmtFinType2_Unf
170   10.782376   Exterior2nd_Plywood
130   10.707123        KitchenQual_TA

In [46]:
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

完成したmodel2のスコア＝0.7960218940921331

In [47]:
#vifが大きいものを選択
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 28]

#4列dropしてみる
to_drop = set(df_high_vif['features'])
for c in to_drop:
    sc_x = sc_x.drop([c], axis = 1)

#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor              features
110   27.008619        FireplaceQu_NA
10    24.705651             GrLivArea
54    22.475783    Neighborhood_NAmes
99    20.689968   Exterior1st_VinylSd
42    18.680007          ExterQual_TA
59    18.112330  Neighborhood_OldTown
94    15.836130   Exterior1st_HdBoard
162   15.789927   Exterior2nd_HdBoard
8     15.459261              1stFlrSF
109   15.360314        FireplaceQu_Gd
112   14.427033        FireplaceQu_TA
41    14.293249          ExterQual_Gd
4     14.223058             YearBuilt
47    13.541525  Neighborhood_CollgCr
169   13.227893   Exterior2nd_Wd Sdng
100   13.147387   Exterior1st_Wd Sdng
63    12.554302  Neighborhood_Somerst
226   11.753363           BsmtQual_TA
182   11.727245       Condition2_Norm
164   11.716862   Exterior2nd_MetalSd
144   11.397529      BsmtFinType2_Unf
49    11.353001  Neighborhood_Edwards
166   10.709567   Exterior2nd_Plywood
128   10.697699        KitchenQual_TA
200   10.316637     HouseStyle_1Story

完成したmodel2のスコア＝0.795079666769221

In [48]:
#vifが大きいものを選択
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 18.5]

#4列dropしてみる
to_drop = set(df_high_vif['features'])
for c in to_drop:
    sc_x = sc_x.drop([c], axis = 1)

#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor             features
4     13.906200            YearBuilt
91    13.359459  Exterior1st_HdBoard
157   13.227892  Exterior2nd_HdBoard
177   11.707513      Condition2_Norm
221   11.399673          BsmtQual_TA
139   11.309360     BsmtFinType2_Unf
164   11.126744  Exterior2nd_Wd Sdng
96    10.833053  Exterior1st_Wd Sdng

完成したmodel2のスコア＝0.7971109145093969

In [49]:
#dropしてみる
sc_x = sc_x.drop(['YearBuilt', 'Exterior1st_HdBoard', 'Condition2_Norm', 'BsmtQual_TA'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

KeyboardInterrupt:

In [ ]:
#dropしてみる
sc_x = sc_x.drop(['BsmtFinType2_Unf'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 5]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor               features
114    9.790953         Functional_Typ
121    9.712928         KitchenQual_TA
161    8.190216    Exterior2nd_Wd Sdng
18     7.643792             GarageCars
94     7.642908    Exterior1st_Wd Sdng
76     7.536515       Foundation_PConc
120    7.334261         KitchenQual_Gd
19     7.019464             GarageArea
7      6.936213               1stFlrSF
191    6.676330      HouseStyle_1Story
59     6.502066   Neighborhood_Somerst
75     6.493975      Foundation_CBlock
16     5.873545             Fireplaces
15     5.865594           TotRmsAbvGrd
194    5.718973      HouseStyle_2Story
216    5.673743            BsmtQual_NA
74     5.669974               Fence_NA
201    5.330487            MSZoning_FV
139    5.325320        Condition1_Norm
25     5.314496               PoolArea
189    5.208942            SaleType_WD
37     5.134821  SaleCondition_Partial
2      5.080260            OverallQual

完成したmodel2のスコア＝0.7965658597529965

In [ ]:
#VIFの最大値が10以下になるよう特徴量を削除した場合、model2のスコアは0.796となった。改変前のスコアは0.777であった。

In [ ]:
#主成分分析にて多重共線性の解消を目指す
df1 = pd.read_csv('datafiles/df2_after_drop.csv')

sc_x = df1.drop(['SalePrice'], axis = 1)
df_y = pd.DataFrame(df1['SalePrice'])

In [ ]:
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

      VIF_Factor              features
123  2202.752816       GarageFinish_NA
22   2178.616803           GarageYrBlt
236   960.199106        MiscFeature_NA
238   802.650747      MiscFeature_Shed
113   283.746702         GarageCond_TA
..           ...                   ...
53     11.641993  Neighborhood_Edwards
184    11.246911   Exterior2nd_Wd Shng
139    10.947886        KitchenQual_TA
134    10.738728          Heating_Grav
131    10.127932        Functional_Typ

[76 rows x 2 columns]

In [ ]:
sc_x.columns

Index([     'MSSubClass',     'LotFrontage',         'LotArea',
           'OverallQual',     'OverallCond',       'YearBuilt',
          'YearRemodAdd',      'MasVnrArea',      'BsmtFinSF1',
             'BsmtUnfSF',
       ...
             'PoolQC_Fa',       'PoolQC_Gd',     'BsmtQual_Fa',
           'BsmtQual_Gd',     'BsmtQual_NA',     'BsmtQual_TA',
       'LandContour_HLS', 'LandContour_Low', 'LandContour_Lvl',
                       0],
      dtype='object', length=247)

In [ ]:
#GarageFinish列をダミー変数化した列一覧をリスト化し、主成分分析により一列化
GarageFinish_cols = []
for c in sc_x.columns:
    if 'GarageFinish_' in c:
        GarageFinish_cols.append(c)
print(GarageFinish_cols)

TypeError: argument of type 'int' is not iterable

In [ ]:

PCAmodel = PCA(whiten = True)
GarageFinish_df = pd.DataFrame()
for c in GarageFinish_cols:
    GarageFinish_df = pd.concat([GarageFinish_df, sc_x[c]], axis = 1)
PCAmodel.fit(GarageFinish_df)
GarageFinish = PCAmodel.transform(sc_x[GarageFinish_cols])

#累積寄与率の閾値を0.8として、n_componentsを設定
thred = 0.8
final_num = 0
ratio =PCAmodel.explained_variance_ratio_
array = []
for i in range(len(ratio)):
    ruiseki = sum(ratio[0:i+1])    #i+1個めの特徴量までの累積寄与率
    if ruiseki > thred:   #i+1個めの特徴量において初めて累積寄与率がthredを超えるならば
          final_num = i
          break
PCAmodel = PCA(n_components = final_num, whiten = True)
PCAmodel.fit(sc_x[GarageFinish_cols])
GarageFinish = PCAmodel.transform(sc_x[GarageFinish_cols])
GarageFinish = pd.DataFrame(GarageFinish)

for c in sc_x[GarageFinish_cols]:
    sc_x = sc_x.drop([c], axis = 1)
sc_x = pd.concat([sc_x, GarageFinish], axis = 1)





result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

In [ ]:
#主成分分析で列を減らす（多重共線性の解消も目指す）