#列の削除により多重共線性の解消を目指す

In [1]:
#import
import pandas as pd
from sklearn.model_selection import train_test_split  #データの分割

from sklearn.preprocessing import StandardScaler #標準化
from sklearn.model_selection import KFold #K分割交差検証
from sklearn.model_selection import cross_validate  #K分割交差検証

from sklearn.linear_model import LinearRegression #回帰
from sklearn.preprocessing import PolynomialFeatures  #交互作用特徴量
from sklearn.linear_model import Ridge  #リッジ回帰
from sklearn.linear_model import Lasso  #ラッソ回帰
from sklearn.tree import DecisionTreeRegressor  #回帰木

from statsmodels.stats.outliers_influence import variance_inflation_factor  #VIF
from sklearn.decomposition import PCA  #PCA

In [2]:
#データフレームの読み込み
'''
df1 VIFの高さを解消するために一部の列を消去する前のデータフレーム
df2 〃した後のデータフレーム

以降は基本的にdf2を用いて分析を行う。
sc_x,df_yはdf2を基に作成する。
ただし、必要があればdf1も利用する。
'''
df2 = pd.read_csv('datafiles/df2_after_drop.csv')

sc_x = df2.drop(['SalePrice'], axis = 1)
df_y = pd.DataFrame(df2['SalePrice'])

In [3]:
print(df2.columns)

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtUnfSF',
       ...
       'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN',
       'Condition2_RRAe', 'Condition2_RRAn', 'Condition2_RRNn',
       'GarageFinish_NA', 'GarageFinish_RFn', 'GarageFinish_Unf', 'SalePrice'],
      dtype='object', length=250)

In [4]:
#K分割交差検証のための準備
kf=KFold(n_splits=5, shuffle=True, random_state=0)

In [5]:
#各種モデルの作成

#重回帰
model1 = LinearRegression()
model1.fit(sc_x, df_y)

#リッジ回帰
model2 = Ridge(alpha = 100)
model2.fit(sc_x, df_y)

#ラッソ回帰
model3 = Lasso(alpha = 100)
model3.fit(sc_x, df_y)

#回帰木
model4 = DecisionTreeRegressor(max_depth = 10, random_state = 0)
model4.fit(sc_x, df_y)

DecisionTreeRegressor(max_depth=10, random_state=0)

In [6]:
#依然として多重共線性は高いため、今後も多重共線性の解消を目指す。

#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 100]
display(df_high_vif)

      VIF_Factor             features
22   2178.616803          GarageYrBlt
56    960.199106       MiscFeature_NA
58    802.650747     MiscFeature_Shed
71    105.805972  Exterior2nd_VinylSd
124   115.837730  Exterior1st_VinylSd
149   233.699047        GarageQual_TA
163   283.746702        GarageCond_TA
183   165.010225      RoofStyle_Gable
185   153.477931        RoofStyle_Hip
246  2202.752816      GarageFinish_NA

In [7]:
#一列dropしてみる
sc_x = sc_x.drop(['GarageFinish_NA'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 100]
display(df_high_vif)

model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor             features
56   959.675823       MiscFeature_NA
58   802.110365     MiscFeature_Shed
71   105.785392  Exterior2nd_VinylSd
124  115.837134  Exterior1st_VinylSd
149  233.384665        GarageQual_TA
163  282.411676        GarageCond_TA
183  164.851995      RoofStyle_Gable
185  153.344617        RoofStyle_Hip

完成したmodel2のスコア＝0.7788228561257453

In [8]:
#一列dropしてみる
sc_x = sc_x.drop(['MiscFeature_NA'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 100]
display(df_high_vif)

model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor             features
70   105.733960  Exterior2nd_VinylSd
123  115.678525  Exterior1st_VinylSd
148  233.363856        GarageQual_TA
162  282.329291        GarageCond_TA
182  164.851570      RoofStyle_Gable
184  153.344550        RoofStyle_Hip

完成したmodel2のスコア＝0.7788175817571734

In [9]:
#3列dropしてみる
sc_x = sc_x.drop(['Exterior2nd_VinylSd', 'GarageCond_TA', 'RoofStyle_Gable'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 100]
display(df_high_vif)

#スコアの確認
model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

Empty DataFrame
Columns: [VIF_Factor, features]
Index: []

完成したmodel2のスコア＝0.7785744518848134

In [10]:
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]

df_high_vif.sort_values('VIF_Factor', ascending=False)

     VIF_Factor               features
128   90.503234           ExterCond_TA
151   81.381629      GarageType_Attchd
126   76.363708           ExterCond_Gd
173   74.401726       RoofMatl_CompShg
155   65.809905      GarageType_Detchd
147   54.715176          GarageQual_TA
22    53.575630            GarageYrBlt
49    51.800551           SaleType_New
118   51.486680    Exterior1st_MetalSd
76    49.162602            MSZoning_RL
199   49.072046  SaleCondition_Partial
10    43.956054            TotalBsmtSF
184   40.031633           Heating_GasA
65    39.593469    Exterior2nd_MetalSd
8     37.100650             BsmtFinSF1
9     35.761214              BsmtUnfSF
0     34.873864             MSSubClass
116   34.013490    Exterior1st_HdBoard
115   33.156910    Exterior1st_CemntBd
77    32.885288            MSZoning_RM
177   32.648732       RoofMatl_Tar&Grv
162   32.531442          MasVnrType_NA
62    29.027080    Exterior2nd_CmentBd
122   28.505460    Exterior1st_VinylSd
161   28.089114     MasVnrType_BrkFace
123   27.864077    Exterior1st_Wd Sdng
95    27.322952         FireplaceQu_NA
13    25.309143              GrLivArea
185   24.150621           Heating_GasW
211   22.874896     Neighborhood_NAmes
11    21.162622               1stFlrSF
153   20.879792     GarageType_BuiltIn
144   20.646135          GarageQual_Fa
63    20.591755    Exterior2nd_HdBoard
216   19.026102   Neighborhood_OldTown
194   18.806107           ExterQual_TA
168   18.789566       BsmtFinType2_Unf
179   18.143395       RoofMatl_WdShngl
125   17.526563           ExterCond_Fa
74    17.397190            MSZoning_FV
119   17.378668    Exterior1st_Plywood
178   17.015940       RoofMatl_WdShake
70    16.863430    Exterior2nd_Wd Sdng
81    16.580265        BldgType_TwnhsE
94    15.414809         FireplaceQu_Gd
5     14.713069              YearBuilt
97    14.515866         FireplaceQu_TA
193   14.458799           ExterQual_Gd
204   13.848010   Neighborhood_CollgCr
87    13.559739      HouseStyle_1Story
67    13.209854    Exterior2nd_Plywood
54    13.180815            BsmtQual_NA
220   12.837224   Neighborhood_Somerst
55    11.979665            BsmtQual_TA
236   11.886476        Condition2_Norm
163   11.832241       MasVnrType_Stone
206   11.626184   Neighborhood_Edwards
139   10.825210         KitchenQual_TA
186   10.723085           Heating_Grav
110   10.097838         Functional_Typ

In [11]:
#3列dropしてみる
sc_x = sc_x.drop(['ExterCond_TA', 'GarageType_Attchd'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
df_high_vif.sort_values('VIF_Factor', ascending=False)

     VIF_Factor               features
171   74.294750       RoofMatl_CompShg
146   54.692519          GarageQual_TA
49    51.798480           SaleType_New
118   51.119943    Exterior1st_MetalSd
197   49.071613  SaleCondition_Partial
76    49.044799            MSZoning_RL
10    43.948652            TotalBsmtSF
182   40.008059           Heating_GasA
65    39.335555    Exterior2nd_MetalSd
8     37.071897             BsmtFinSF1
9     35.731590              BsmtUnfSF
22    35.464462            GarageYrBlt
0     34.836645             MSSubClass
116   33.819178    Exterior1st_HdBoard
115   32.987842    Exterior1st_CemntBd
77    32.768803            MSZoning_RM
175   32.608835       RoofMatl_Tar&Grv
160   32.516718          MasVnrType_NA
62    28.944317    Exterior2nd_CmentBd
122   28.428503    Exterior1st_VinylSd
159   28.086050     MasVnrType_BrkFace
123   27.674552    Exterior1st_Wd Sdng
95    27.317552         FireplaceQu_NA
13    25.262063              GrLivArea
183   24.140066           Heating_GasW
209   22.850034     Neighborhood_NAmes
11    21.160379               1stFlrSF
143   20.640083          GarageQual_Fa
63    20.561693    Exterior2nd_HdBoard
214   18.996966   Neighborhood_OldTown
192   18.785049           ExterQual_TA
166   18.775727       BsmtFinType2_Unf
177   18.123505       RoofMatl_WdShngl
74    17.340506            MSZoning_FV
119   17.304836    Exterior1st_Plywood
176   16.995623       RoofMatl_WdShake
70    16.822239    Exterior2nd_Wd Sdng
81    16.572072        BldgType_TwnhsE
94    15.413045         FireplaceQu_Gd
5     14.712815              YearBuilt
97    14.514807         FireplaceQu_TA
191   14.455322           ExterQual_Gd
202   13.844727   Neighborhood_CollgCr
87    13.538958      HouseStyle_1Story
67    13.193579    Exterior2nd_Plywood
54    13.179801            BsmtQual_NA
218   12.828973   Neighborhood_Somerst
55    11.947524            BsmtQual_TA
234   11.877318        Condition2_Norm
161   11.829309       MasVnrType_Stone
204   11.607898   Neighborhood_Edwards
138   10.776370         KitchenQual_TA
184   10.716540           Heating_Grav
110   10.096010         Functional_Typ

In [12]:
#スコアの確認
model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

完成したmodel2のスコア＝0.7786656098208722

In [13]:
#4列dropしてみる
sc_x = sc_x.drop(['RoofMatl_CompShg', 'GarageQual_TA', 'SaleType_New', 'Exterior1st_MetalSd'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

     VIF_Factor              features
75    48.946791           MSZoning_RL
10    43.205565           TotalBsmtSF
178   39.953988          Heating_GasA
8     36.797813            BsmtFinSF1
9     35.658095             BsmtUnfSF
0     34.745525            MSSubClass
76    32.669914           MSZoning_RM
157   32.515975         MasVnrType_NA
114   28.835127   Exterior1st_CemntBd
156   28.079813    MasVnrType_BrkFace
61    28.019531   Exterior2nd_CmentBd
94    27.075910        FireplaceQu_NA
13    24.909164             GrLivArea
179   24.117283          Heating_GasW
205   22.839742    Neighborhood_NAmes
120   21.745307   Exterior1st_VinylSd
11    21.004793              1stFlrSF
210   18.971534  Neighborhood_OldTown
163   18.758056      BsmtFinType2_Unf
188   18.737500          ExterQual_TA
73    17.270353           MSZoning_FV
115   16.946186   Exterior1st_HdBoard
80    16.547138       BldgType_TwnhsE
62    16.035793   Exterior2nd_HdBoard
93    15.364833        FireplaceQu_Gd
121   14.751391   Exterior1st_Wd Sdng
5     14.506338             YearBuilt
96    14.466238        FireplaceQu_TA
187   14.393154          ExterQual_Gd
198   13.826444  Neighborhood_CollgCr
69    13.665718   Exterior2nd_Wd Sdng
86    13.272611     HouseStyle_1Story
53    12.974457           BsmtQual_NA
214   12.748268  Neighborhood_Somerst
64    12.255745   Exterior2nd_MetalSd
54    11.892308           BsmtQual_TA
230   11.861105       Condition2_Norm
158   11.825406      MasVnrType_Stone
200   11.601421  Neighborhood_Edwards
66    10.894903   Exterior2nd_Plywood
136   10.722481        KitchenQual_TA
180   10.703671          Heating_Grav
109   10.073144        Functional_Typ

In [14]:
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

完成したmodel2のスコア＝0.7786075560896861

In [15]:
#4列dropしてみる
sc_x = sc_x.drop(['MSZoning_RL', 'TotalBsmtSF', 'Heating_GasA', 'BsmtFinSF1'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

     VIF_Factor              features
0     34.608125            MSSubClass
154   32.438191         MasVnrType_NA
111   28.758254   Exterior1st_CemntBd
153   28.017892    MasVnrType_BrkFace
59    27.951783   Exterior2nd_CmentBd
91    27.019800        FireplaceQu_NA
11    24.884128             GrLivArea
201   22.784311    Neighborhood_NAmes
117   21.672533   Exterior1st_VinylSd
184   18.709625          ExterQual_TA
206   18.441342  Neighborhood_OldTown
112   16.883913   Exterior1st_HdBoard
77    16.458552       BldgType_TwnhsE
60    15.852241   Exterior2nd_HdBoard
9     15.555781              1stFlrSF
90    15.362034        FireplaceQu_Gd
118   14.709670   Exterior1st_Wd Sdng
93    14.447351        FireplaceQu_TA
183   14.383612          ExterQual_Gd
5     14.364998             YearBuilt
194   13.782718  Neighborhood_CollgCr
67    13.542481   Exterior2nd_Wd Sdng
83    13.188947     HouseStyle_1Story
210   12.717934  Neighborhood_Somerst
62    12.205471   Exterior2nd_MetalSd
52    11.847475           BsmtQual_TA
155   11.780496      MasVnrType_Stone
226   11.754728       Condition2_Norm
196   11.545700  Neighborhood_Edwards
160   11.440429      BsmtFinType2_Unf
64    10.782376   Exterior2nd_Plywood
133   10.707123        KitchenQual_TA

In [16]:
#スコアの確認
model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

完成したmodel2のスコア＝0.7960218940921336

In [17]:
#vifが大きいものを選択
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 28]

#4列dropしてみる
to_drop = set(df_high_vif['features'])
for c in to_drop:
    sc_x = sc_x.drop([c], axis = 1)

#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

#スコアの確認
model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor              features
90    27.008619        FireplaceQu_NA
10    24.705651             GrLivArea
197   22.475783    Neighborhood_NAmes
115   20.689968   Exterior1st_VinylSd
180   18.680007          ExterQual_TA
202   18.112330  Neighborhood_OldTown
110   15.836130   Exterior1st_HdBoard
59    15.789927   Exterior2nd_HdBoard
8     15.459261              1stFlrSF
89    15.360314        FireplaceQu_Gd
92    14.427033        FireplaceQu_TA
179   14.293249          ExterQual_Gd
4     14.223058             YearBuilt
190   13.541525  Neighborhood_CollgCr
66    13.227893   Exterior2nd_Wd Sdng
116   13.147387   Exterior1st_Wd Sdng
206   12.554302  Neighborhood_Somerst
51    11.753363           BsmtQual_TA
222   11.727245       Condition2_Norm
61    11.716862   Exterior2nd_MetalSd
156   11.397529      BsmtFinType2_Unf
192   11.353001  Neighborhood_Edwards
63    10.709567   Exterior2nd_Plywood
131   10.697699        KitchenQual_TA
82    10.316637     HouseStyle_1Story

完成したmodel2のスコア＝0.7950796667692217

In [18]:
#vifが大きいものを選択
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 18.5]

#4列dropしてみる
to_drop = set(df_high_vif['features'])
for c in to_drop:
    sc_x = sc_x.drop([c], axis = 1)

#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

#スコアの確認
model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor             features
4     13.906200            YearBuilt
108   13.359459  Exterior1st_HdBoard
58    13.227892  Exterior2nd_HdBoard
217   11.707513      Condition2_Norm
50    11.399673          BsmtQual_TA
153   11.309360     BsmtFinType2_Unf
65    11.126744  Exterior2nd_Wd Sdng
113   10.833053  Exterior1st_Wd Sdng

完成したmodel2のスコア＝0.7971109145093968

In [19]:
#drop後のデータフレームを保存
df3_lowered_VIF = pd.concat([sc_x, df_y], axis = 1)
df3_lowered_VIF.to_csv('df3_lowered_VIF.csv', index=False)

In [20]:
#dropしてみる
sc_x = sc_x.drop(['YearBuilt', 'Exterior1st_HdBoard', 'Condition2_Norm', 'BsmtQual_TA'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 10]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

#スコアの確認
model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor          features
150   11.286445  BsmtFinType2_Unf

完成したmodel2のスコア＝0.7963257043346245

In [21]:
#dropしてみる
sc_x = sc_x.drop(['BsmtFinType2_Unf'], axis = 1)
#vifを見る
vif_df = pd.DataFrame()
vif_df["VIF_Factor"] = [variance_inflation_factor(sc_x, i) for i in range(sc_x.shape[1])]
vif_df["features"]=sc_x.columns
df_high_vif = vif_df.loc[vif_df['VIF_Factor'] >= 5]
display(df_high_vif.sort_values('VIF_Factor', ascending=False))

#スコアの確認
model2.fit(sc_x, df_y)
result = cross_validate(model2, sc_x, df_y, cv = kf, scoring = 'r2' , return_train_score = True)
print(f'完成したmodel2のスコア＝{sum(result['test_score'])/len(result['test_score'])}')

     VIF_Factor               features
101    9.790953         Functional_Typ
125    9.712928         KitchenQual_TA
63     8.190216    Exterior2nd_Wd Sdng
18     7.643792             GarageCars
110    7.642908    Exterior1st_Wd Sdng
202    7.536515       Foundation_PConc
124    7.334261         KitchenQual_Gd
19     7.019464             GarageArea
7      6.936213               1stFlrSF
79     6.676330      HouseStyle_1Story
197    6.502066   Neighborhood_Somerst
201    6.493975      Foundation_CBlock
16     5.873545             Fireplaces
15     5.865594           TotRmsAbvGrd
82     5.718973      HouseStyle_2Story
48     5.673743            BsmtQual_NA
77     5.669974               Fence_NA
67     5.330487            MSZoning_FV
116    5.325320        Condition1_Norm
25     5.314496               PoolArea
45     5.208942            SaleType_WD
177    5.134821  SaleCondition_Partial
2      5.080260            OverallQual

完成したmodel2のスコア＝0.7965658597529963

In [22]:
#VIFの最大値が10以下になるよう特徴量を削除した場合、model2のスコアは最高で0.797となった。改変前のスコアは0.777であった。
#スコアが最高であったときの学習用データを保存した。