In [19]:
'''
分析用テーブルを用いて統計解析を行う。
'''

'\n分析用テーブルを用いて統計解析を行う。\n'

In [20]:
import pandas as pd

In [21]:
#SQLとの連携
from getpass import getpass
from sqlalchemy import create_engine, text

password = getpass("MySQL password: ")
engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/pakistan_ecommerce"
)

In [22]:
query = """
-- データ件数を確認
SELECT COUNT(*)
FROM ecommerce_analysis;
"""
df = pd.read_sql(query, engine)
display(df)

   COUNT(*)
0   1048564

In [23]:
#テーブルをデータフレームに変更
query = """
SELECT *
FROM ecommerce_analysis
"""
df = pd.read_sql(query, engine)

In [24]:
df.shape

(1048564, 6)

In [25]:
display(df.head(10))
display(df.tail(10))

     category_name_1 payment_method  year  month customer_since  grand_total
0    Women's Fashion            cod  2016      7         2016-7       1950.0
1  Beauty & Grooming            cod  2016      7         2016-7        240.0
2    Women's Fashion            cod  2016      7         2016-7       2450.0
3  Beauty & Grooming            cod  2016      7         2016-7         60.0
4            Soghaat            cod  2016      7         2016-7       1110.0
5            Soghaat            cod  2016      7         2016-7         80.0
6  Beauty & Grooming            cod  2016      7         2016-7         60.0
7            Soghaat            cod  2016      7         2016-7        170.0
8  Mobiles & Tablets  ublcreditcard  2016      7         2016-7      96499.0
9  Mobiles & Tablets      mygateway  2016      7         2016-7      96499.0

,category_name_1,payment_method,year,month,customer_since,grand_total
1048554,,,0,0,,0.0
1048555,,,0,0,,0.0
1048556,,,0,0,,0.0
1048557,,,0,0,,0.0
1048558,,,0,0,,0.0
1048559,,,0,0,,0.0
1048560,,,0,0,,0.0
1048561,,,0,0,,0.0
1048562,,,0,0,,0.0
1048563,,,0,0,,0.0

In [26]:
display(df.tail(10).to_string())

'        category_name_1 payment_method  year  month customer_since  grand_total\n1048554                                    0      0                         0.0\n1048555                                    0      0                         0.0\n1048556                                    0      0                         0.0\n1048557                                    0      0                         0.0\n1048558                                    0      0                         0.0\n1048559                                    0      0                         0.0\n1048560                                    0      0                         0.0\n1048561                                    0      0                         0.0\n1048562                                    0      0                         0.0\n1048563                                    0      0                         0.0'

In [27]:
null_index = df[
    (df['year'] == 0) 
    & (df['month'] == 0)
    & (df['grand_total'] == 0.0)
]
display(null_index.index)

Index([ 584513,  584514,  584515,  584516,  584517,  584518,  584519,  584520,
        584521,  584522,
       ...
       1048554, 1048555, 1048556, 1048557, 1048558, 1048559, 1048560, 1048561,
       1048562, 1048563],
      dtype='int64', length=464051)

In [28]:
null_index.value_counts()

category_name_1  payment_method  year  month  customer_since  grand_total
                                 0     0                      0.0            464051
Name: count, dtype: int64

In [33]:
'''
上の2セルより、インデックス584513～1048563の行は意味がない。よって削除する。
'''
df=df.loc[:584512,:]

In [34]:
for c in df.columns:
    print(f'列＝{c}')
    display(df[c].value_counts())

列＝category_name_1

category_name_1
Mobiles & Tablets     115710
Men's Fashion          92219
Women's Fashion        59720
Appliances             52413
Superstore             43613
Beauty & Grooming      41494
Soghaat                34011
Others                 29212
Home & Living          26504
Entertainment          26326
Health & Sports        17502
Kids & Baby            16494
Computing              15933
School & Education      3478
Books                   1870
                         164
Name: count, dtype: int64

列＝payment_method

payment_method
cod                  271955
Payaxis               97640
Easypay               82896
jazzwallet            35145
easypay_voucher       31176
bankalfalah           23065
jazzvoucher           15633
Easypay_MA            14027
customercredit         7555
apg                    1758
ublcreditcard           882
cashatdoorstep          732
mcblite                 723
mygateway               669
internetbanking         472
productcredit           125
marketingexpense         45
financesettlement        15
Name: count, dtype: int64

列＝year

year
2017    290920
2018    159684
2016    133909
Name: count, dtype: int64

列＝month

month
11    155456
5      62603
3      61482
8      48514
7      39151
2      38777
6      34530
4      34091
10     30623
12     29199
1      26063
9      24024
Name: count, dtype: int64

列＝customer_since

customer_since
2016-11    82714
2017-11    70785
2016-7     57069
2016-9     46746
2017-5     35356
2018-3     32052
2018-2     23989
2016-8     21051
2017-8     19088
2017-3     18234
2016-10    17546
2017-4     16826
2018-5     16076
2017-6     15593
2017-10    14618
2017-7     14035
2017-1     12260
2016-12    10638
2017-2     10293
2018-1      9665
2017-12     8667
2018-4      7626
2017-9      7442
2018-6      6798
2018-7      5330
2018-8      4016
Name: count, dtype: int64

列＝grand_total

grand_total
0.0        9632
1000.0     5145
2000.0     3780
2500.0     3235
5000.0     2912
           ...
11086.0       1
38439.0       1
2012.2        1
27317.0       1
11023.0       1
Name: count, Length: 36813, dtype: int64

In [ ]:
'''
grand_total == 0.0 の行が9632件も存在する。これがどのような場合なのか、元データにさかのぼって確認する。
'''

query = """
SELECT DISTINCT item_id, status, price, discount_amount, qty_ordered
FROM ecommerce_orders
WHERE grand_total = 0.0
AND NOT year = 0
AND NOT discount_amount = 0
;
"""

display(pd.read_sql(query, engine))

      item_id    status    price  discount_amount  qty_ordered
0      211823  complete      1.0             1.00          1.0
1      211886  complete      1.0             1.00          1.0
2      212275  complete      1.0             1.00          1.0
3      212387  complete      1.0             1.00          1.0
4      212388  complete      1.0             1.00          1.0
...       ...       ...      ...              ...          ...
2781   893858  received    995.0           200.00          1.0
2782   897592  received  29890.0          1000.00          1.0
2783   898961  received  21146.0          2000.00          1.0
2784   899252  received   3499.5           303.56          1.0
2785   899254  received    295.0           303.56          1.0

[2786 rows x 5 columns]

In [41]:
query = """
SELECT DISTINCT item_id, status, price, discount_amount, qty_ordered
FROM ecommerce_orders
WHERE grand_total = 0.0
AND NOT year = 0
AND discount_amount = 0
;
"""

display(pd.read_sql(query, engine))

      item_id          status    price  discount_amount  qty_ordered
0      211146        complete    320.0              0.0          1.0
1      211157  order_refunded   1000.0              0.0          1.0
2      211162        complete    500.0              0.0          1.0
3      211163        complete    100.0              0.0          5.0
4      211422        complete    995.0              0.0          1.0
...       ...             ...      ...              ...          ...
6841   904904            paid    837.0              0.0          1.0
6842   905028            paid  20599.0              0.0          1.0
6843   905080            paid    799.0              0.0          1.0
6844   905196            paid   1299.0              0.0          1.0
6845   905198            paid    999.0              0.0          1.0

[6846 rows x 5 columns]

In [ ]:
'''
grand_total == 0.0 の列は grand_total = price * qty_ordered - discount_amount の式に適さない。
加えて、キャンセルや返金が起こったケースを意味するわけでもないと考えられる。
'''

In [ ]:
query = """
SELECT
    increment_id,
    item_id,
    status,
    price,
    discount_amount,
    qty_ordered,
    grand_total
FROM ecommerce_orders
WHERE grand_total = 0
  AND NOT year = 0
  AND discount_amount = 0
LIMIT 50;
"""

display(pd.read_sql(query, engine))

,increment_id,item_id,status,price,discount_amount,qty_ordered,grand_total
0,100147456,211146,complete,320.0,0.0,1.0,0.0
1,100147461,211157,order_refunded,1000.0,0.0,1.0,0.0
2,100147463,211162,complete,500.0,0.0,1.0,0.0
3,100147463,211163,complete,100.0,0.0,5.0,0.0
4,100147648,211422,complete,995.0,0.0,1.0,0.0
5,100147686,211472,complete,320.0,0.0,1.0,0.0
6,100147867,211704,complete,799.0,0.0,1.0,0.0
7,100147896,211743,order_refunded,999.0,0.0,1.0,0.0
8,100147977,211854,complete,585.0,0.0,1.0,0.0
9,100147998,211889,complete,1650.0,0.0,1.0,0.0
10,100147998,211891,complete,959.0,0.0,1.0,0.0
11,100147998,211893,complete,299.0,0.0,1.0,0.0
12,100147998,211894,complete,299.0,0.0,1.0,0.0
13,100147998,211895,complete,1200.0,0.0,1.0,0.0
14,100148046,212050,complete,6240.0,0.0,1.0,0.0
15,100148046,212051,complete,700.0,0.0,1.0,0.0
16,100148046,212053,complete,899.0,0.0,1.0,0.0
17,100148126,212162,complete,120.0,0.0,1.0,0.0
18,100148244,212365,refund,695.0,0.0,1.0,0.0
19,100148280,212414,canceled,700.0,0.0,1.0,0.0
20,100148282,212417,canceled,399.0,0.0,1.0,0.0
21,100148284,212419,canceled,399.0,0.0,1.0,0.0
22,100148358,212524,complete,525.0,0.0,2.0,0.0
23,100148444,212644,complete,1761.0,0.0,1.0,0.0
24,100148445,212645,complete,450.0,0.0,2.0,0.0
25,100148506,212758,complete,699.0,0.0,1.0,0.0
26,100148506,212760,complete,525.0,0.0,1.0,0.0
27,100148620,212925,complete,875.0,0.0,1.0,0.0
28,100148620,212926,complete,400.0,0.0,1.0,0.0
29,100148620,212927,complete,625.0,0.0,1.0,0.0
30,100148635,212947,complete,790.0,0.0,1.0,0.0
31,100148679,213033,complete,75.0,0.0,1.0,0.0
32,100148681,213036,complete,3861.0,0.0,1.0,0.0
33,100148725,213104,complete,190.0,0.0,1.0,0.0
34,100148845,213305,order_refunded,875.0,0.0,1.0,0.0
35,100148858,213318,closed,512.0,0.0,1.0,0.0
36,100148858,213319,closed,156.0,0.0,1.0,0.0
37,100148890,213360,refund,700.0,0.0,1.0,0.0
38,100148917,213405,complete,700.0,0.0,1.0,0.0
39,100148928,213426,complete,1499.0,0.0,1.0,0.0
40,100148930,213428,complete,655.0,0.0,1.0,0.0
41,100148933,213440,complete,599.0,0.0,1.0,0.0
42,100148937,213445,complete,210.0,0.0,1.0,0.0
43,100148937,213446,complete,210.0,0.0,1.0,0.0
44,100148961,213480,order_refunded,2.0,0.0,1.0,0.0
45,100148968,213491,order_refunded,2.0,0.0,1.0,0.0
46,100148988,213517,complete,410.0,0.0,1.0,0.0
47,100149037,213580,complete,350.0,0.0,1.0,0.0
48,100149038,213581,complete,3000.0,0.0,1.0,0.0
49,100149039,213582,complete,1499.0,0.0,1.0,0.0

In [48]:
query = """
SELECT *
FROM ecommerce_orders
WHERE 100147454 < increment_id
AND increment_id < 100147459
AND NOT year = 0;
"""
table=pd.read_sql(query, engine)
display(table.T)

,0,1,2,3,4,5
item_id,211145,211146,211147,211149,211150,211151
status,complete,complete,canceled,complete,complete,complete
created_at,7/1/2016,7/1/2016,7/1/2016,7/1/2016,7/1/2016,7/1/2016
sku,kcc_Sultanat,kcc_glamour deal,Assetmen_MD-346-M,cr_DATES WITH CASHEW-400 GM,UK_Gift Box Mix Dry Fruit Sweets 500 Gms,itter_AB 1199
price,120.0,320.0,1550.0,420.0,360.0,490.0
qty_ordered,1.0,1.0,1.0,1.0,1.0,1.0
grand_total,120.0,0.0,1550.0,1270.0,1270.0,1270.0
increment_id,100147455,100147456,100147457,100147458,100147458,100147458
category_name_1,Home & Living,Beauty & Grooming,Men's Fashion,Soghaat,Soghaat,Beauty & Grooming
sales_commission_code,105259,None,105259,R-KHW-104406,R-KHW-104406,R-KHW-104406
discount_amount,0.0,0.0,0.0,0.0,0.0,0.0
payment_method,ublcreditcard,customercredit,ublcreditcard,cod,cod,cod
working_date,7/1/2016,7/1/2016,7/1/2016,7/1/2016,7/1/2016,7/1/2016
bi_status,Net,Net,Gross,Net,Net,Net
mv,120,320,"1,550",420,360,490
year,2016,2016,2016,2016,2016,2016
month,7,7,7,7,7,7
customer_since,2016-7,2016-7,2016-7,2016-7,2016-7,2016-7
m_y,7-2016,7-2016,7-2016,7-2016,7-2016,7-2016
fy,FY17,FY17,FY17,FY17,FY17,FY17
customer_id,11,12,11,13,13,13

In [49]:
'''
前のセルの実行結果より、grand_total	は一人が一回にする注文ごとに計算されていると分かった。
したがって、grand_totalをそのまま目的変数に使うのは不適切である。
以降は、
indeed_price = price * qty_ordered - discount_amount
を目的変数とする。
'''

'\n前のセルの実行結果より、grand_total\tは一人が一回にする注文ごとに計算されていると分かった。\nしたがって、grand_totalをそのまま目的変数に使うのは不適切である。\n以降は、\nindeed_price = price * qty_ordered - discount_amount\nを目的変数とする。\n'

In [52]:
'''
インデックス584513～1048563の行 ⇔ year == 0　の行
だとここまでの分析により判明しているため、これらの行はテーブル作成の際に取り除く。
'''

#分析に使うデータだけのSQLテーブル ecommerce_analysis2 を作成
query = """
CREATE TABLE ecommerce_analysis2
SELECT category_name_1, payment_method, year, month, customer_since,  (price * qty_ordered - discount_amount) AS indeed_price
FROM  ecommerce_orders
WHERE NOT customer_since = '#N/A'
AND NOT year = 0
;
"""

with engine.begin() as conn:
    result = conn.execute(text(query))

In [53]:
query = """
SHOW TABLES;
"""
df = pd.read_sql(query, engine)
display(df)

  Tables_in_pakistan_ecommerce
0           ecommerce_analysis
1          ecommerce_analysis2
2             ecommerce_orders

In [55]:
query = """
SELECT *
FROM ecommerce_analysis2
LIMIT 10;
"""
df = pd.read_sql(query, engine)
display(df)

     category_name_1 payment_method  year  month customer_since  indeed_price
0    Women's Fashion            cod  2016      7         2016-7        1950.0
1  Beauty & Grooming            cod  2016      7         2016-7         240.0
2    Women's Fashion            cod  2016      7         2016-7        2450.0
3  Beauty & Grooming            cod  2016      7         2016-7          60.0
4            Soghaat            cod  2016      7         2016-7        1110.0
5            Soghaat            cod  2016      7         2016-7          80.0
6  Beauty & Grooming            cod  2016      7         2016-7          60.0
7            Soghaat            cod  2016      7         2016-7         170.0
8  Mobiles & Tablets  ublcreditcard  2016      7         2016-7       96499.0
9  Mobiles & Tablets      mygateway  2016      7         2016-7       96499.0

In [56]:
query = """
-- データ件数を確認
SELECT COUNT(*)
FROM ecommerce_analysis2;
"""
df = pd.read_sql(query, engine)
display(df)

   COUNT(*)
0    584513

In [ ]:
#分析用のテーブルを作成したため、操作上の利便性の観点から、今後の分析は別のファイルで行う。