In [29]:
'''
校正したテーブルecommerce_analysis3を用いて、回帰分析を開始する。
'''

'\n校正したテーブルecommerce_analysis3を用いて、回帰分析を開始する。\n'

In [30]:
#Python関連のimport
import pandas as pd
from sklearn.model_selection import train_test_split  #データの分割

from sklearn.tree import DecisionTreeClassifier  #決定木（標準化は不要）
from sklearn.preprocessing import PolynomialFeatures  #交互作用特徴量

from sklearn.linear_model import Ridge  #リッジ回帰

In [31]:
#SQLとの連携
from getpass import getpass
from sqlalchemy import create_engine, text

password = getpass("MySQL password: ")
engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/pakistan_ecommerce"
)

In [32]:
query = """
-- データ件数を確認
SELECT COUNT(*)
FROM ecommerce_analysis3;
"""
df = pd.read_sql(query, engine)
display(df)

   COUNT(*)
0    584513

In [33]:
#テーブルをデータフレームに変更
query = """
SELECT *
FROM ecommerce_analysis3
"""
df = pd.read_sql(query, engine)

In [34]:
display(df.head(10))
display(df.tail(10))

,category_name_1,payment_method,year,month,customer_since,grand_total,increment_id
0,Women's Fashion,cod,2016,7,2016-7,1950.0,100147443
1,Beauty & Grooming,cod,2016,7,2016-7,240.0,100147444
2,Women's Fashion,cod,2016,7,2016-7,2450.0,100147445
3,Beauty & Grooming,cod,2016,7,2016-7,60.0,100147446
4,Soghaat,cod,2016,7,2016-7,1110.0,100147447
5,Soghaat,cod,2016,7,2016-7,80.0,100147448
6,Beauty & Grooming,cod,2016,7,2016-7,60.0,100147449
7,Soghaat,cod,2016,7,2016-7,170.0,100147450
8,Mobiles & Tablets,ublcreditcard,2016,7,2016-7,96499.0,100147451
9,Mobiles & Tablets,mygateway,2016,7,2016-7,96499.0,100147452

,category_name_1,payment_method,year,month,customer_since,grand_total,increment_id
584503,Men's Fashion,customercredit,2018,8,2018-6,0.0,100562381
584504,Men's Fashion,customercredit,2018,8,2018-6,0.0,100562381
584505,Mobiles & Tablets,jazzvoucher,2018,8,2016-9,13770.0,100562382
584506,Women's Fashion,cod,2018,8,2018-8,550.0,100562383
584507,Women's Fashion,cod,2018,8,2018-8,649.0,100562384
584508,Women's Fashion,cod,2018,8,2018-8,849.0,100562385
584509,Mobiles & Tablets,bankalfalah,2018,8,2018-8,35899.0,100562386
584510,Mobiles & Tablets,bankalfalah,2018,8,2018-7,652178.0,100562387
584511,Mobiles & Tablets,bankalfalah,2018,8,2018-7,652178.0,100562387
584512,Mobiles & Tablets,bankalfalah,2018,8,2018-7,652178.0,100562387

In [35]:
#customer_sinceを基に、顧客である期間（月）を計算する。

# customer_since を文字列として処理
customer_since = df['customer_since'].astype('string')

# 年と月を分離
since_year = customer_since.str.extract(r'(\d{4})-(\d{1,2})')[0]
since_month = customer_since.str.extract(r'(\d{4})-(\d{1,2})')[1]

# 数値化
since_year = pd.to_numeric(since_year, errors = 'coerce')
since_month = pd.to_numeric(since_month, errors = 'coerce')

# 顧客である期間（月）
df['customer_duration'] = (
    (df['year'] - since_year) * 12
    + (df['month'] - since_month)
)

display(df.head(10))

,category_name_1,payment_method,year,month,customer_since,grand_total,increment_id,customer_duration
0,Women's Fashion,cod,2016,7,2016-7,1950.0,100147443,0
1,Beauty & Grooming,cod,2016,7,2016-7,240.0,100147444,0
2,Women's Fashion,cod,2016,7,2016-7,2450.0,100147445,0
3,Beauty & Grooming,cod,2016,7,2016-7,60.0,100147446,0
4,Soghaat,cod,2016,7,2016-7,1110.0,100147447,0
5,Soghaat,cod,2016,7,2016-7,80.0,100147448,0
6,Beauty & Grooming,cod,2016,7,2016-7,60.0,100147449,0
7,Soghaat,cod,2016,7,2016-7,170.0,100147450,0
8,Mobiles & Tablets,ublcreditcard,2016,7,2016-7,96499.0,100147451,0
9,Mobiles & Tablets,mygateway,2016,7,2016-7,96499.0,100147452,0

In [36]:
#'category_name_1',  'payment_method'はダミー変数化する。この後、ダミー変数の列も足し合わせるのでdrop_first=False
dummy1 = pd.get_dummies(df['category_name_1'],drop_first=False,dtype=int)
dummy2 = pd.get_dummies(df['payment_method'],drop_first=False,dtype=int)
df2 = pd.concat([df,dummy1,dummy2],axis=1)
print(df2.columns)

Index(['category_name_1', 'payment_method', 'year', 'month', 'customer_since',
       'grand_total', 'increment_id', 'customer_duration', '', 'Appliances',
       'Beauty & Grooming', 'Books', 'Computing', 'Entertainment',
       'Health & Sports', 'Home & Living', 'Kids & Baby', 'Men's Fashion',
       'Mobiles & Tablets', 'Others', 'School & Education', 'Soghaat',
       'Superstore', 'Women's Fashion', 'Easypay', 'Easypay_MA', 'Payaxis',
       'apg', 'bankalfalah', 'cashatdoorstep', 'cod', 'customercredit',
       'easypay_voucher', 'financesettlement', 'internetbanking',
       'jazzvoucher', 'jazzwallet', 'marketingexpense', 'mcblite', 'mygateway',
       'productcredit', 'ublcreditcard'],
      dtype='object')

In [37]:
df2=df2.drop(['category_name_1', 'customer_since', 'payment_method'],axis=1)
#increment_idが同じものを足す（'year', 'month','customer_duration', 'grand_total', 'increment_id' は除く）
df2=df2.sort_values(by = 'increment_id',ascending=True)
df2.head(5)

,year,month,grand_total,increment_id,customer_duration,,Appliances,Beauty & Grooming,Books,Computing,...,easypay_voucher,financesettlement,internetbanking,jazzvoucher,jazzwallet,marketingexpense,mcblite,mygateway,productcredit,ublcreditcard
82291,2016,11,332.0,100001290,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
182318,2017,4,1149.0,100002382,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,2016,7,1950.0,100147443,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2016,7,240.0,100147444,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2016,7,2450.0,100147445,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
df2.columns

Index(['year', 'month', 'grand_total', 'increment_id', 'customer_duration', '',
       'Appliances', 'Beauty & Grooming', 'Books', 'Computing',
       'Entertainment', 'Health & Sports', 'Home & Living', 'Kids & Baby',
       'Men's Fashion', 'Mobiles & Tablets', 'Others', 'School & Education',
       'Soghaat', 'Superstore', 'Women's Fashion', 'Easypay', 'Easypay_MA',
       'Payaxis', 'apg', 'bankalfalah', 'cashatdoorstep', 'cod',
       'customercredit', 'easypay_voucher', 'financesettlement',
       'internetbanking', 'jazzvoucher', 'jazzwallet', 'marketingexpense',
       'mcblite', 'mygateway', 'productcredit', 'ublcreditcard'],
      dtype='object')

In [40]:
display(df2.groupby('increment_id').sum())

,year,month,grand_total,customer_duration,,Appliances,Beauty & Grooming,Books,Computing,Entertainment,...,easypay_voucher,financesettlement,internetbanking,jazzvoucher,jazzwallet,marketingexpense,mcblite,mygateway,productcredit,ublcreditcard
increment_id,,,,,,,,,,,,,,,,,,,,,
100001290,2016,11,332.0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
100002382,2017,4,1149.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100147443,2016,7,1950.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100147444,2016,7,240.0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100147445,2016,7,2450.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100562383,2018,8,550.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100562384,2018,8,649.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100562385,2018,8,849.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100562386,2018,8,35899.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100562387,6054,24,1956534.0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
#１注文あたり１行になるよう直したデータをdf4とする。

df3=pd.DataFrame()
sum_cols = [
    '', 'Appliances', 'Beauty & Grooming', 'Books', 'Computing',
       'Entertainment', 'Health & Sports', 'Home & Living', 'Kids & Baby',
       'Men\'s Fashion', 'Mobiles & Tablets', 'Others', 'School & Education',
       'Soghaat', 'Superstore', 'Women\'s Fashion', 'Easypay', 'Easypay_MA',
       'Payaxis', 'apg', 'bankalfalah', 'cashatdoorstep', 'cod',
       'customercredit', 'easypay_voucher', 'financesettlement',
       'internetbanking', 'jazzvoucher', 'jazzwallet', 'marketingexpense',
       'mcblite', 'mygateway', 'productcredit', 'ublcreditcard'
]
not_sum_cols = ['year', 'month','customer_duration', 'grand_total']

df3 = df2.groupby('increment_id')[sum_cols].sum()
df4 = df3.join(
   df2.groupby('increment_id')[not_sum_cols].first()
)
df4 = df4.reset_index()

In [52]:
display(df4.head(10))

,increment_id,,Appliances,Beauty & Grooming,Books,Computing,Entertainment,Health & Sports,Home & Living,Kids & Baby,...,jazzwallet,marketingexpense,mcblite,mygateway,productcredit,ublcreditcard,year,month,customer_duration,grand_total
0,100001290,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,2016,11,0,332.0
1,100002382,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2017,4,0,1149.0
2,100147443,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2016,7,0,1950.0
3,100147444,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,2016,7,0,240.0
4,100147445,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2016,7,0,2450.0
5,100147446,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,2016,7,0,60.0
6,100147447,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2016,7,0,1110.0
7,100147448,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2016,7,0,80.0
8,100147449,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,2016,7,0,60.0
9,100147450,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2016,7,0,170.0

In [ ]:
ids=pd.DataFrame(df4['increment_id'])
ids.value_counts().sort_values(ascending=True)
#このセルの結果より、increment_idに重複がないと示された。

increment_id
100001290       1
100147447       1
100147448       1
100147449       1
100147450       1
               ..
100562339       1
100562364       1
100562362       1
100562342       1
100562387       1
Name: count, Length: 408773, dtype: int64

In [ ]:
#以下、df4を用いて回帰分析を行う。