In [ ]:
'''
校正したテーブルecommerce_analysis2を用いて、回帰分析を開始する。
説明変数の列＝['category_name_1',  'payment_method', 'year', 'month', 'customer_since']
目的変数の列＝['indeed_payment']
'''

In [3]:
import pandas as pd

In [1]:
#SQLとの連携
from getpass import getpass
from sqlalchemy import create_engine, text

password = getpass("MySQL password: ")
engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/pakistan_ecommerce"
)

In [5]:
query = """
-- データ件数を確認
SELECT COUNT(*)
FROM ecommerce_analysis2;
"""
df = pd.read_sql(query, engine)
display(df)

   COUNT(*)
0    584513

In [7]:
#テーブルをデータフレームに変更
query = """
SELECT *
FROM ecommerce_analysis2
"""
df = pd.read_sql(query, engine)

In [8]:
df.shape

(584513, 6)

In [9]:
display(df.head(10))
display(df.tail(10))

     category_name_1 payment_method  year  month customer_since  indeed_price
0    Women's Fashion            cod  2016      7         2016-7        1950.0
1  Beauty & Grooming            cod  2016      7         2016-7         240.0
2    Women's Fashion            cod  2016      7         2016-7        2450.0
3  Beauty & Grooming            cod  2016      7         2016-7          60.0
4            Soghaat            cod  2016      7         2016-7        1110.0
5            Soghaat            cod  2016      7         2016-7          80.0
6  Beauty & Grooming            cod  2016      7         2016-7          60.0
7            Soghaat            cod  2016      7         2016-7         170.0
8  Mobiles & Tablets  ublcreditcard  2016      7         2016-7       96499.0
9  Mobiles & Tablets      mygateway  2016      7         2016-7       96499.0

,category_name_1,payment_method,year,month,customer_since,indeed_price
584503,Men's Fashion,customercredit,2018,8,2018-6,1299.0
584504,Men's Fashion,customercredit,2018,8,2018-6,999.0
584505,Mobiles & Tablets,jazzvoucher,2018,8,2016-9,13520.0
584506,Women's Fashion,cod,2018,8,2018-8,400.0
584507,Women's Fashion,cod,2018,8,2018-8,499.0
584508,Women's Fashion,cod,2018,8,2018-8,699.0
584509,Mobiles & Tablets,bankalfalah,2018,8,2018-8,35599.0
584510,Mobiles & Tablets,bankalfalah,2018,8,2018-7,259998.0
584511,Mobiles & Tablets,bankalfalah,2018,8,2018-7,174600.0
584512,Mobiles & Tablets,bankalfalah,2018,8,2018-7,217280.0

In [10]:
display(df.tail(10).to_string())

"          category_name_1  payment_method  year  month customer_since  indeed_price\n584503      Men's Fashion  customercredit  2018      8         2018-6        1299.0\n584504      Men's Fashion  customercredit  2018      8         2018-6         999.0\n584505  Mobiles & Tablets     jazzvoucher  2018      8         2016-9       13520.0\n584506    Women's Fashion             cod  2018      8         2018-8         400.0\n584507    Women's Fashion             cod  2018      8         2018-8         499.0\n584508    Women's Fashion             cod  2018      8         2018-8         699.0\n584509  Mobiles & Tablets     bankalfalah  2018      8         2018-8       35599.0\n584510  Mobiles & Tablets     bankalfalah  2018      8         2018-7      259998.0\n584511  Mobiles & Tablets     bankalfalah  2018      8         2018-7      174600.0\n584512  Mobiles & Tablets     bankalfalah  2018      8         2018-7      217280.0"