In [33]:
'''
分析用テーブルを用いて統計解析を行う。
'''

'\n分析用テーブルを用いて統計解析を行う。\n'

In [34]:
import pandas as pd

In [35]:
#SQLとの連携
from getpass import getpass
from sqlalchemy import create_engine, text

password = getpass("MySQL password: ")
engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/pakistan_ecommerce"
)

In [36]:
query = """
-- データ件数を確認
SELECT COUNT(*)
FROM ecommerce_analysis;
"""
df = pd.read_sql(query, engine)
display(df)

   COUNT(*)
0   1048564

In [37]:
#テーブルをデータフレームに変更
query = """
SELECT *
FROM ecommerce_analysis
"""
df = pd.read_sql(query, engine)

In [38]:
df.shape

(1048564, 6)

In [39]:
display(df.head(10))
display(df.tail(10))

     category_name_1 payment_method  year  month customer_since  grand_total
0    Women's Fashion            cod  2016      7         2016-7       1950.0
1  Beauty & Grooming            cod  2016      7         2016-7        240.0
2    Women's Fashion            cod  2016      7         2016-7       2450.0
3  Beauty & Grooming            cod  2016      7         2016-7         60.0
4            Soghaat            cod  2016      7         2016-7       1110.0
5            Soghaat            cod  2016      7         2016-7         80.0
6  Beauty & Grooming            cod  2016      7         2016-7         60.0
7            Soghaat            cod  2016      7         2016-7        170.0
8  Mobiles & Tablets  ublcreditcard  2016      7         2016-7      96499.0
9  Mobiles & Tablets      mygateway  2016      7         2016-7      96499.0

,category_name_1,payment_method,year,month,customer_since,grand_total
1048554,,,0,0,,0.0
1048555,,,0,0,,0.0
1048556,,,0,0,,0.0
1048557,,,0,0,,0.0
1048558,,,0,0,,0.0
1048559,,,0,0,,0.0
1048560,,,0,0,,0.0
1048561,,,0,0,,0.0
1048562,,,0,0,,0.0
1048563,,,0,0,,0.0

In [46]:
display(df.tail(10).to_string())

'        category_name_1 payment_method  year  month customer_since  grand_total\n1048554                                    0      0                         0.0\n1048555                                    0      0                         0.0\n1048556                                    0      0                         0.0\n1048557                                    0      0                         0.0\n1048558                                    0      0                         0.0\n1048559                                    0      0                         0.0\n1048560                                    0      0                         0.0\n1048561                                    0      0                         0.0\n1048562                                    0      0                         0.0\n1048563                                    0      0                         0.0'

In [47]:
null_index = df[
    (df['year'] == 0) 
    & (df['month'] == 0)
    & (df['grand_total'] == 0.0)
]
display(null_index.index)

Index([ 584513,  584514,  584515,  584516,  584517,  584518,  584519,  584520,
        584521,  584522,
       ...
       1048554, 1048555, 1048556, 1048557, 1048558, 1048559, 1048560, 1048561,
       1048562, 1048563],
      dtype='int64', length=464051)

In [48]:
null_index.value_counts()

category_name_1  payment_method  year  month  customer_since  grand_total
                                 0     0                      0.0            464051
Name: count, dtype: int64

In [ ]:
'''
上の2セルより、インデックス584513～1048563の行は意味がない。よって削除する。
'''
df=df.loc(584513:1048563,:)