In [4]:
'''
＜分析の流れ＞

SQLによりデータベースの前処理
↓
pandasによりデータの前処理
↓
統計解析
'''

'\n＜分析の流れ＞\n\nSQLによりデータベースの前処理\n↓\npandasによりデータの前処理\n↓\n統計解析\n'

In [5]:
'''
SQLによりデータベースの前処理をする。
'''

'\nSQLによりデータベースの前処理をする。\n'

In [8]:
import pandas as pd

In [15]:
#SQLとの連携
from getpass import getpass
from sqlalchemy import create_engine, text

password = getpass("MySQL password: ")
engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/pakistan_ecommerce"
)

In [ ]:
query = """
-- 使用するデータベースを選択
USE pakistan_ecommerce;
"""
with engine.begin() as conn:
    result = conn.execute(text(query))

In [17]:
query = """
-- データベース内のテーブルを確認
SHOW TABLES;
"""
df = pd.read_sql(query, engine)
display(df)

  Tables_in_pakistan_ecommerce
0             ecommerce_orders

In [18]:
query = """
-- データ件数を確認
SELECT COUNT(*)
FROM ecommerce_orders;
"""
df = pd.read_sql(query, engine)
display(df)

   COUNT(*)
0   1048575

In [19]:
query = """
-- データを確認
SELECT *
FROM ecommerce_orders
LIMIT 10;
"""
df = pd.read_sql(query, engine)
display(df)

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,working_date,bi_status,mv,year,month,customer_since,m_y,fy,customer_id
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,None,...,cod,7/1/2016,#REF!,"1,950",2016,7,2016-7,7-2016,FY17,1
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,None,...,cod,7/1/2016,Gross,240,2016,7,2016-7,7-2016,FY17,2
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,None,...,cod,7/1/2016,Gross,"2,450",2016,7,2016-7,7-2016,FY17,3
3,211135,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,cod,7/1/2016,Net,360,2016,7,2016-7,7-2016,FY17,4
4,211136,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,None,...,cod,7/1/2016,Valid,"1,110",2016,7,2016-7,7-2016,FY17,5
5,211137,canceled,7/1/2016,UK_Namkino All In One 200 Gms,80.0,1.0,80.0,100147448,Soghaat,None,...,cod,7/1/2016,Gross,80,2016,7,2016-7,7-2016,FY17,6
6,211138,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147449,Beauty & Grooming,None,...,cod,7/1/2016,Net,360,2016,7,2016-7,7-2016,FY17,7
7,211139,complete,7/1/2016,UK_Namkino Mix Nimco 400 Gms,170.0,1.0,170.0,100147450,Soghaat,None,...,cod,7/1/2016,Net,170,2016,7,2016-7,7-2016,FY17,6
8,211140,canceled,7/1/2016,Apple iPhone 6S 64GB,96499.0,1.0,96499.0,100147451,Mobiles & Tablets,None,...,ublcreditcard,7/1/2016,Gross,"96,499",2016,7,2016-7,7-2016,FY17,8
9,211141,canceled,7/1/2016,Apple iPhone 6S 64GB,96499.0,1.0,96499.0,100147452,Mobiles & Tablets,None,...,mygateway,7/1/2016,Gross,"96,499",2016,7,2016-7,7-2016,FY17,8