#各月の気温・降水量・日照時間と、スーパー・百貨店での衣料品の売り上げの相関

In [2]:
#import

import pandas as pd
!conda install openpyxl

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda

In [8]:
#データの読み込み

df_x = pd.read_csv(r'C:\Users\natsu\myworks_for_GitHub\Python-machine-learning-study-log\opendata_analysis\datafiles\crimate_data.csv',encoding="cp932")
df_t = pd.read_excel(r'C:\Users\natsu\myworks_for_GitHub\Python-machine-learning-study-log\opendata_analysis\datafiles\h2slt61j.xlsx')


display(df_x.head(10))
display(df_t.head(10))

                                                                                                                                                                                                                                           ダウンロードした時刻：2026/06/26 14:52:38
NaN    東京          東京          東京          東京          東京          東京          東京         東京         東京         東京         東京       東京       東京       東京       東京        東京        東京        東京      東京      東京      東京         東京                                     東京
年月     日最高気温の平均(℃) 日最高気温の平均(℃) 日最高気温の平均(℃) 日最低気温の平均(℃) 日最低気温の平均(℃) 日最低気温の平均(℃) 降水量の合計(mm) 降水量の合計(mm) 降水量の合計(mm) 降水量の合計(mm) 日照時間(時間) 日照時間(時間) 日照時間(時間) 日照時間(時間) 平均風速(m/s) 平均風速(m/s) 平均風速(m/s) 平均湿度(％) 平均湿度(％) 平均湿度(％) 平均雲量(10分比) 平均雲量(10分比)                     平均雲量(10分比)
NaN    NaN         品質情報        均質番号        NaN         品質情報        均質番号        NaN        現象なし情報     品質情報       均質番号       NaN      現象なし情報   品質情報     均質番号     NaN       品質情報      均質番号      NaN     品質情報    均質番号    NaN        品質情報                                 均質番号
2005/1 10.0        8           1           2.6         8           1           77.0       0          8          1          200.0    0        8        1        3.7       8         1         47      8       1       4.2        8                                       1
2005/2 9.9         8           1           2.5         8           1           48.0       0          8          1          148.9    0        8        1        3.9       8         1         45      8       1       6.3        8                                       1
2005/3 13.1        8           1           5.0         8           1           71.0       0          8          1          175.1    0        8        1        3.5       8         1         49      8       1       6.0        8                                       1
2005/4 19.6        8           1           10.7        8           1           81.0       0          8          1          216.1    0        8        1        3.8       8         1         54      8       1       5.4        8                                       1
2005/5 21.9        8           1           14.1        8           1           180.5      0          8          1          172.3    0        8        1        3.9       8         1         58      8       1       7.2        8                                       1
2005/6 26.7        8           1           20.2        8           1           170.5      0          8          1          119.3    0        8        1        3.0       8         1         70      8       1       8.9        8                                       1
2005/7 29.1        8           1           22.6        8           1           247.5      0          8          1          103.9    0        8        1        2.9       8         1         71      8       1       8.9        8                                       1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,百貨店・スーパー商品別販売額指数 2020年基準,NaN,NaN,NaN,NaN,NaN
3,NaN,Indices of Departmentstores and Supermarkets s...,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,（１）原指数,NaN,NaN,NaN,Original indices
6,NaN,NaN,NaN,四半期 Q1～Q4,NaN,NaN,NaN
7,NaN,NaN,NaN,月次 Monthly,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,（２）季節調整済指数,NaN,NaN,NaN,Seasonal adjustment indices

In [ ]:
#データの成型

df_x2=df_x.drop(index=(0,1),axis=0) 
df_t2=df_t.drop(index=range(0,8),axis=0)